name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/azure-static-web-apps-ci-cd.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'

env:
  NODE_VERSION: '18'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --coverage --watchAll=false
        env:
          CI: true

      - name: Build application
        run: npm run build
        env:
          # Environment-specific build variables
          REACT_APP_USE_API: ${{ github.ref == 'refs/heads/main' && 'true' || 'true' }}
          REACT_APP_API_BASE_URL: ${{ github.ref == 'refs/heads/main' && secrets.REACT_APP_API_BASE_URL_PROD || secrets.REACT_APP_API_BASE_URL_DEV }}
          CI: false

      - name: Deploy to Azure Static Web Apps (Production)
        if: github.ref == 'refs/heads/main'
        id: builddeploy-prod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "build"
          skip_app_build: true
        env:
          NODE_VERSION: ${{ env.NODE_VERSION }}

      - name: Deploy to Azure Static Web Apps (Development)
        if: github.ref == 'refs/heads/develop'
        id: builddeploy-dev
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "build"
          skip_app_build: true
        env:
          NODE_VERSION: ${{ env.NODE_VERSION }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request (Production)
        if: github.base_ref == 'main'
        id: closepullrequest-prod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          action: "close"

      - name: Close Pull Request (Development)
        if: github.base_ref == 'develop'
        id: closepullrequest-dev
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          action: "close"